### ISSUE TITLE
Using the same user on the rabbit brooker

### ISSUE THREAD

**Issue by scwall** [overhangio/tutor#383]
**Bug description**
hello, 

There is currently a problem with using Rabbit which uses the same login and password with LMS and CMS, I have encountered a conflict when sending mass emails. 

```
LMS ---> rabbitmq --> worker-cms
                  |-->worker-lms
```

Here LMS sends the task to rabbit who sends it to the most responsive docker took the message first (CMS) which returned an error that the task does not exist. The LMS worker listened to receive that there was a task but received nothing neither task nor error.

To fix the problem I used a dirty way to do it in the meantime, I used the plugin system and overide the configuration file and now everything works.

The two ways I see are either the same docker rabbitmq and two different identifiers created in the Dockerfile , or leave two separate rabbit containers for each worker.

my current plugins
```
name: tworabbitdockers
version: 0.1.0
patches:
  lms-env: |
    "CELERY_BROKER_HOSTNAME": "rabbitmq-lms"

  cms-env: |
    "CELERY_BROKER_HOSTNAME": "rabbitmq-cms"

  local-docker-compose-services: |
    ########### LMS and CMS rabbitmq
    rabbitmq-lms:
      image: docker.io/rabbitmq:3.6.10-management-alpine
      volumes:
        - ../../data/rabbitmq:/var/lib/rabbitmq
      restart: unless-stopped

    rabbitmq-cms:
      image: docker.io/rabbitmq:3.6.10-management-alpine
      volumes:
        - ../../data/rabbitmq:/var/lib/rabbitmq
      restart: unless-stopped

```
