### ISSUE TITLE
use of mailhog for email tests

### ISSUE THREAD

**Issue by scwall** [overhangio/tutor#384]
Hello,
here is for more facility currently I use mailhog for the tests of email, it is free and makes it possible to avoid third services, I added it as plugins and behind nginx like reverse proxy to keep a safety, it is possible to put a password behind mailhog directly in a Dockerfile if I am not mistaken, but I found it simpler for the dev with nginx

use in **config.yml** file tutor for dev
SMTP_HOST: mailhog
SMTP_PORT: 25

```
name: mailhogfordev
version: 0.1.0
patches:
  local-docker-compose-services: |
    ########### mailhog for dev
    mailhog:
        image: mailhog/mailhog:v1.0.0

    nginx-mailhog-proxy:
      image: quay.io/dtan4/nginx-basic-auth-proxy:latest
      ports:
        - 8025:80
      environment:
        - BASIC_AUTH_USERNAME= chooseusername
        - BASIC_AUTH_PASSWORD= choosepassword
        - PROXY_PASS=http://mailhog:8025/

```
