### ISSUE TITLE
kustomization.yml in env folder is not standard yaml format——tutor version 13.3.1

### ISSUE THREAD

**Issue by afutureboss** [overhangio/tutor#714]
**Bug description**

```
configMapGenerator:
- name: caddy-config
  files:
  - apps/caddy/Caddyfile
  options:
    labels:
           app.kubernetes.io/name: caddy
- name: openedx-settings-lms
  files:
  - apps/openedx/settings/lms/__init__.py
  - apps/openedx/settings/lms/development.py
  - apps/openedx/settings/lms/production.py
  - apps/openedx/settings/lms/test.py
  options:
    labels:
           app.kubernetes.io/name: openedx
- name: openedx-settings-cms
  files:
  - apps/openedx/settings/cms/__init__.py
  - apps/openedx/settings/cms/development.py
  - apps/openedx/settings/cms/production.py
  - apps/openedx/settings/cms/test.py
  options:
    labels:
           app.kubernetes.io/name: openedx
- name: openedx-config
  files:
  - apps/openedx/config/cms.env.json
  - apps/openedx/config/lms.env.json
  options:
    labels:
           app.kubernetes.io/name: openedx
- name: redis-config
  files:
  - apps/redis/redis.conf
  options:
    labels:
          app.kubernetes.io/name: redis
```

**How to reproduce**
there is 4 indent on configMapGenerator->options->labels->...... which will lead kubectl apply errror "json: unknown field "options""

**Environment**
tutor version 13.3.1

**Additional context**
