### ISSUE TITLE
Annotations are ignored while executing tutor k8s start caddy

### ISSUE THREAD

**Issue by g-vijayvergia** [overhangio/tutor#879]
**Bug description**

Annotations are not being processed by tutor in Kubernetes env. Refer to annotations section [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).

**How to reproduce**

Set the following annotations as part of the Kubernetes service.yml and deploy tutor via OKE service in oracle cloud.

```
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: loadbalancer
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
```

The annotations section is ignored by tutor while executing tutor k8s start. It will create a standard load balancer with wrong type and there will be no ssl certificate is configured on Load Balancer even though it is being explicitly passed via the annotations.

**Environment**
Oracle Cloud (OKE service)
