### ISSUE TITLE
Image build fails when `OPENEDX_EXTRA_PIP_REQUIREMENTS` has value pointing to local path

### ISSUE THREAD

**Issue by ziafazal** [overhangio/tutor#968]
**Bug description**
Building `openedx-dev` image fails when `OPENEDX_EXTRA_PIP_REQUIREMENTS` has value pointing to local path.

I have set value of `OPENEDX_EXTRA_PIP_REQUIREMENTS` to a package which is in one of my explicit mounts
```
tutor config printvalue OPENEDX_EXTRA_PIP_REQUIREMENTS 
['-e /openedx/src/openedx-cmi5-xblock']

``````
Running tutor command `tutor images build openedx-dev`  to build `openedx-dev` image failed with this error

 > [python-requirements  7/10] RUN --mount=type=cache,target=/openedx/.cache/pip,sharing=shared     pip install '-e /openedx/src/openedx-cmi5-xblock':
#0 0.325 ERROR:  /openedx/src/openedx-cmi5-xblock is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

```
Tutor version 17.0.0

**Comment by regisb** [comment]
What is the output of `tutor mounts list`?

**Comment by ziafazal** [comment]
> What is the output of `tutor mounts list`?

```
- name: /Users/ziaulhaq/docker/edx-platform
  build_mounts:
  - image: openedx
    context: edx-platform
  - image: openedx-dev
    context: edx-platform
  compose_mounts:
  - service: openedx
    container_path: /openedx/edx-platform
- name: openedx:/Users/ziaulhaq/docker/src:/openedx/src
  build_mounts: []
  compose_mounts:
  - service: openedx
    container_path: /openedx/src

```

**Comment by regisb** [comment]
Right. Explicit mounts are not mounted at build time. Thus, the /openedx/src directory is not mounted during build, which causes the build to fail.

Instead, I suggest you use the brand new auto-mounted Python package directories: https://docs.tutor.edly.io/tutorials/edx-platform.html#working-on-edx-platform-python-dependencies

Start by removing your current mount:

    tutor mounts remove /Users/ziaulhaq/docker/src

Mount your xblock:

    tutor mounts add /openedx/src/openedx-cmi5-xblock

Check that the xblock directory will be bind-mounted at build time with:

    tutor mounts list

**Comment by ziafazal** [comment]
I'm still getting similar error after auto mounting my xblock and removing previously created explicit mount
```
RUN --mount=type=cache,target=/openedx/.cache/pip,sharing=shared     pip install '-e /mnt/openedx-cmi5-xblock':
#0 0.455 ERROR:  /mnt/openedx-cmi5-xblock is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

Here is output of `tutor mounts list` now
```
- name: /Users/ziaulhaq/docker/edx-platform
  build_mounts:
  - image: openedx
    context: edx-platform
  - image: openedx-dev
    context: edx-platform
  compose_mounts:
  - service: openedx
    container_path: /openedx/edx-platform
- name: /Users/ziaulhaq/docker/src/openedx-cmi5-xblock
  build_mounts:
  - image: openedx
    context: mnt-openedx-cmi5-xblock
  - image: openedx-dev
    context: mnt-openedx-cmi5-xblock
  compose_mounts:
  - service: openedx
    container_path: /mnt/openedx-cmi5-xblock
  - service: openedx-dev
    container_path: /mnt/openedx-cmi5-xblock

```
