### ISSUE TITLE
`tutor mounts add /path-to-openedx-scorm-xblock` doesn't automatically install scorm-xblock

### ISSUE THREAD

**Issue by Danyal-Faheem** [overhangio/tutor#997]
**Bug description**

Using the latest mounting command `tutor mounts add /path-to-xblock`, I tried to install [scorm-xblock](https://github.com/overhangio/openedx-scorm-xblock) in my tutor install. This was on a fresh install of tutor and only the default plugins were installed as well. However, tutor did not install scorm-xblock after I had mounted it using the above mentioned command and did not show up in the Advanced tab on a studio course even after I had added `scorm` to the advanced settings list.

**How to reproduce**

On a fresh install of tutor quince 17.0, you can follow the following steps to reproduce the command.

- Clone [scorm-xblock](https://github.com/overhangio/openedx-scorm-xblock).
- Run `tutor mounts add path-to-scorm-xblock`
- Run `tutor images build openedx-dev`
- Run `tutor dev stop && tutor dev start -d`
- Create a new course or run `tutor dev do importdemocourse`. Under Advanced Module List In the advanced settings of the course, add `scorm` and save changes. Now, while adding a new unit, you should be able to see Scorm Module as an option in the advanced tab but that is not the case here.

The output of `tutor mounts list` for me is:
```
- name: path-to/openedx-scorm-xblock
  build_mounts:
  - image: openedx
    context: mnt-openedx-scorm-xblock
  - image: openedx-dev
    context: mnt-openedx-scorm-xblock
  compose_mounts:
  - service: openedx
    container_path: /mnt/openedx-scorm-xblock
  - service: openedx-dev
    container_path: /mnt/openedx-scorm-xblock
```
The output of `tutor config printvalue OPENEDX_EXTRA_PIP_REQUIREMENTS` for me is:

`[]`

openedx-scorm-xblock does show for me at the `/mnt` path inside the LMS container.
That is also the solution I am currently utilizing which is to follow the following steps:

- `tutor dev run lms bash`
- `cd /mnt`
- `pip install -e ./openedx-scorm-xblock`
- `exit`
- `tutor dev stop && tutor dev start -d`

After these steps, openedx-scorm-xblock works as intended and hot-reloading works as well as it is installed in editable mode.

Surprisingly enough, while running `tutor images build openedx-dev` after adding the xblock as a mount, it seems that tutor does try to install `openedx-scorm-xblock` in editable mode as can be seen in the screenshot below.

![image](https://github.com/overhangio/tutor/assets/138459282/44ca5c15-6b0a-44c4-9fdd-69fe1fb1d833)

**Environment**

- Tutor: version 17.0.0
- Mac OS: 14.3 (23D56) Arm
- Docker: 4.26.1
